import { v4 as uuidv4 } from 'uuid';
import executeTransaction from '../executeTransaction';
import getAutoGeneratedColumns from '../utilities/getAutoGeneratedColumns';

export default async function insertObjectsTreeTrunkTablesNotIsSystem(
  tablesData: Array<{
    table: string;
    dataIn: Array<{ [key: string]: any }>;
    parentField: string;
    childField: string;
  }>
): Promise<{
  data: Array<{
    table: string;
    dataIn: Object[];
    oldData: Object[];
    parentField: string;
    childField: string;
  }>;
  status: boolean;
  errorCode: string | Object;
}> {
  const resultData: Array<{
    table: string;
    dataIn: Object[];
    oldData: Object[];
    parentField: string;
    childField: string;
  }> = [];

  const { status, errorCode } = await executeTransaction(async (connection) => {
    for (const { table, dataIn, parentField, childField } of tablesData) {
      const { allColumns, autoGeneratedFields } = await getAutoGeneratedColumns(connection, table);
      const hasIsSystem = allColumns.some(col => col.Field === 'isSystem');

      for (const dataInsertRaw of dataIn) {
        const dataInsert = { ...dataInsertRaw };

        // Nếu parentId tồn tại → kiểm tra có hợp lệ không
        const parentId = dataInsert[parentField];
        if (parentId) {
          const [parentRows] = await connection.execute(
            `SELECT ${childField} FROM ${table} WHERE ${childField} = ?`,
            [parentId]
          );
          if ((parentRows as any[]).length === 0) {
            throw { message: `Parent with id ${parentId} not found` };
          }
        }

        // Tạo UUID nếu cần
        if (autoGeneratedFields.includes(childField)) {
          dataInsert[childField] = uuidv4();
        }

        // Gán isSystem = false nếu có
        if (hasIsSystem) {
          dataInsert.isSystem = false;
        }

        // Lọc bỏ các trường tự sinh
        const newRowFiltered = Object.fromEntries(
          Object.entries(dataInsert).filter(([key]) => !autoGeneratedFields.includes(key))
        );

        const sqlString = `INSERT INTO ${table} (${Object.keys(newRowFiltered).join(', ')})
          VALUES (${Object.keys(newRowFiltered).map(() => '?').join(', ')})`;

        await connection.execute(sqlString, Object.values(newRowFiltered));
      }
    }
  });

  // Gán kết quả trả về
  tablesData.forEach(({ table, dataIn, parentField, childField }) => {
    resultData.push({
      table,
      dataIn,
      oldData: [],
      parentField,
      childField
    });
  });

  return { data: resultData, status, errorCode };
}
